const operators = {
  LET: "let",
  CONST: "const",
  ARRAY_EXP: "[]",
  TYPE_OF: "typeof",
  EQUAL: "===",
  NOT_EQUAL: "!==",
  LESS_THAN: "<",
  GREATER_THAN: ">",
  NOT: "!",
  INCREMENT: "++",
  DECREMENT: "--",
  ASSIGN: "=",
  PLUS_ASSIGN: "+=",
  MINUS_ASSIGN: "-=",
  MULTIPLY_ASSIGN: "*=",
  DIVIDE_ASSIGN: "/=",
  MODULO_ASSIGN: "%=",
  COLON: ":",
  DOUBLE_EQUAL: "==",
  NOT_DOUBLE_EQUAL: "!=",
  AND: "&&",
  OR: "||",
  NULLISH_COALESCE: "??",
  OPTIONAL_CHAINING: "?.",
  BITWISE_AND: "&",
  BITWISE_OR: "|",
  BITWISE_XOR: "^",
  BITWISE_NOT: "~",
  BITWISE_LEFT_SHIFT: "<<",
  BITWISE_RIGHT_SHIFT: ">>",
  BITWISE_UNSIGNED_RIGHT_SHIFT: ">>>",
  SPREAD_OPERATOR: "...",
  CONDITIONAL_OPERATOR: "?",
  MEMBER_ACCESS: ".",
  ARROW_FUNCTION: "=>",
};

export default operators;
